openapi: 3.0.1
info:
  title: idv-hub
  description: Verifiable Claims Hub
  version: 1.0.0
servers:
- url: /api/v1
tags:
- name: eKYC OIDC
  description: eKYC OIDC
- name: Specification
  description: The swagger API specification
paths:
  /ekyc/config:
    get:
      tags:
      - Passbase
      description: Get public config
      responses:
        200:
          description: OK
          content: {}
  /ekyc/passbase/{key}:
    get:
      tags:
      - Passbase
      parameters:
      - name: key
        in: path
        description: key from Passbase
        required: true
        schema:
          type: string
      description: Fetch data from passbase
      responses:
        200:
          description: OK
          content: {}
  /ekyc/passbase/all:
    get:
      tags:
      - Passbase
      description: Fetch data from passbase
      responses:
        200:
          description: OK
          content: {}
  /ekyc/vc:
    post:
      tags:
        - Debug
      description: Insert VC for debug purposes
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VCBody'

      responses:
        200:
          description: OK
          content: {}
  /ekyc/vc/my:
    get:
      tags:
      - Passbase
      description: Fetch data from passbase
      responses:
        200:
          description: OK
          content: {}
  /ekyc/vc/claims:
    get:
      tags:
      - Passbase
      description: Fetch data from passbase
      responses:
        200:
          description: OK
          content: {}
  /ekyc/vc/{sub}:
    get:
      tags:
      - Passbase
      parameters:
      - name: sub
        in: path
        description: oidc sub identifier
        required: true
        schema:
          type: string
      description: GEt vc from db
      responses:
        200:
          description: OK
          content: {}
  /ekyc/vc/pending:
    get:
      tags:
      - Passbase
      description: GEt pending vc from db
      responses:
        200:
          description: OK
          content: {}
  /ekyc/vc/{id}:
    delete:
      tags:
      - Passbase
      parameters:
      - name: id
        in: path
        description: oidc sub identifier
        required: true
        schema:
          type: string
      description: Delete vc from db
      responses:
        200:
          description: OK
          content: {}
  /idp/vc/{sub}:
    get:
      tags:
      - Idp
      parameters:
      - name: sub
        in: path
        description: oidc sub identifier
        required: true
        schema:
          type: string
      - name: claims
        in: query
        description: oidc claims requested
        required: true
        schema:
          type: string
      description: GEt vc from db
      responses:
        200:
          description: OK
          content: {}
  /idp/vc:
    post:
      tags:
      - Idp
      description: Get similarity rate of claim
      responses:
        200:
          description: OK
          content: {}
  /idp/verify-claim:
    post:
      tags:
      - Idp
      description: Get similarity rate of claim
      responses:
        200:
          description: OK
          content: {}
  /session:
    post:
      tags:
      - Session
      description: Get new session
      responses:
        200:
          description: OK
          content: {}
  /session/handle:
    post:
      tags:
      - Session
      description: Update the handle from service
      responses:
        200:
          description: OK
          content: {}

  /examples/{id}:
    get:
      tags:
      - Examples
      parameters:
      - name: id
        in: path
        description: The id of the example to retrieve
        required: true
        schema:
          type: integer
      responses:
        200:
          description: Return the example with the specified id
          content: {}
        404:
          description: Example not found
          content: {}
  /spec:
    get:
      tags:
      - Specification
      responses:
        200:
          description: Return the API specification
          content: {}
components:
  schemas:
    VCBody:
      type: object
      properties:
        sub:
          type: string
        status:
          type: string
        verification:
          type: object
        claims:
          type: object
      example:
        sub: 68f81aa8-48dc-11ec-81d3-0242ac130003
        status: FINISHED
        metadata:
          source: 'manual-insert'
          document: 'driving_permit'
        verification:
          evidence:
            - verifier:
                organization: Passbase
                txn: da56c2e3-db5a-42b3-a14a-e33e12452512
              document:
                type: driving_permit
                issuer:
                  name: CITY OF WOLLU
                number: '00339/11/2661'
                date_of_issuance: '2011-07-12'
                date_of_expiry: '2033-01-19'
              type: id_document
              method: uripp
              time: '2020-06-07T08:23:59.763Z'
          trust_framework:
          time: '2020-06-07T08:23:59.763Z'
          verification_process: da56c2e3-db5a-42b3-a14a-e33e12452512
        claims:
          given_name: JOE
          family_name: DOE
          birthdate: '1992-06-20'


